/*
 * $Id: $
 * 
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __BCM_KNETSYNC_H__
#define __BCM_KNETSYNC_H__

#include <bcm/types.h>


#ifndef BCM_HIDE_DISPATCHABLE

/* Initialize the KNETSync ptp clock subsystem and Firmware. */
extern int bcm_knetsync_init(
    int unit);

/* Deinitailize the KNETSync ptp clock subsystem and Firmware. */
extern int bcm_knetsync_deinit(
    int unit);

#endif /* BCM_HIDE_DISPATCHABLE */

#endif /* __BCM_KNETSYNC_H__ */
