/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: $
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 * File:        enum_types.h
 * Purpose:     Definition for fields, memories, registers, formats
 */

#ifndef _SOC_ENUM_TYPES_H
#define _SOC_ENUM_TYPES_H

typedef int soc_reg_t;
typedef int soc_mem_t;
typedef int soc_format_t;
typedef int soc_field_t;

#endif  /* !_SOC_ENUM_TYPES_H */
